version: "3.8"

services:
  db:
    image: mysql
    container_name: bts_demo_db
    restart: always
    volumes:
        - db-data:/var/lib/mysql
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
        - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: bts_demo_phpmyadmin
    restart: always
    depends_on:
        - db
    ports:
        - 8080:80
    environment:
        PMA_HOST: db
    networks:
        - dev

  www:
    build: docker
    container_name: www_bts_demo
    restart: always
    ports:
      - "8741:80"
    volumes:
        - ./docker/vhosts:/etc/apache2/sites-enabled
        - ./:/var/www
    networks:
        - dev

networks:
    dev:

volumes:
    db-data: